ALTER TABLE CLIENTE ADD EmailCli VARCHAR(80);
ALTER TABLE CLIENTE DROP COLUMN EmailCli;
UPDATE PRODUTO SET PrecoProd = 6.00 WHERE CodProd = 10;
DELETE FROM PEDIDOPRODUTO WHERE NumPed = 100 AND CodProd = 11;